# Generated by Django 3.2.13 on 2022-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_company_name_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='generes',
            field=models.JSONField(),
        ),
    ]
